# Generated by add-eq from LCD-2C_USED_EQ.txt.
{
  flake.modules.nixos.equalizer-lcd-2c = {
    services.pipewire.extraConfig.pipewire."99-eq-lcd-2c" = {
      "context.modules" = [
        {
          name = "libpipewire-module-parametric-equalizer";
          args = {
            "equalizer.filepath" = "${./lcd-2c.eq}";
            "equalizer.description" = "DragonFly Red Pro EQ";
            "capture.props" = {
              "media.class" = "Audio/Sink";
              "node.name" = "effect_input.eq_lcd-2c";
            };
            "playback.props" = {
              "node.target" = "alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Red_v1.0_AQDFRD0100115209-00.pro-output-0";
            };
          };
        }
      ];
    };
  };
}
